[package]
name = "clovis"
version = "0.1.0"
edition = "2021"

[dependencies]
dirs = "3.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
log = "0.4"
simple_logger = "1.11.0"
clap = { version = "4.0", features = ["derive"] }
